---
- name: Install MongoDB
  hosts: all
  become: yes
  tasks:
    - name: Add MongoDB GPG key
      shell: wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add -

    - name: Add MongoDB repository
      shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list

    - name: Install libssl dependency
      shell: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
