---
- name: install nginx play
  hosts: web
  gather_facts: yes
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: Install and configure nginx
      apt:
        name: nginx
        state: present