---
- name: Update and upgrade all target nodes
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Apt update
      apt:
        update_cache: yes

    - name: Apt upgrade
      apt:
        upgrade: dist
